<div class="grid-80 prefix-20">
	<h2>Current Pages</h2>
	<?php
		if($this->pages != null) {
			$this->partialLoop()->setObjectKey('page');
	 	echo $this->partialLoop('aurora/partials/page.phtml', $this->pages); ?>

	<?php 
	}
	else {
	?>	
	<p>You do not have any pages yet.</p>
	<?php 
		if(Zend_Auth::getInstance()->hasIdentity() 
			&& $this->acl->isAllowed(Zend_Auth::getInstance()->getIdentity()->role, 'content', 'create')) {
	?>
			<a href='/page-admin/create'>Create a new page</a>
	<?php 
		}
	}
	?>
</div>