<div class="grid-90 page-body">
    <h3><?php echo $this->name; ?></h3>
    <?php 
    
    $nodes = $this->nodes($this->page);
    
    foreach ($nodes as $node) {
    	
		//Zend_Debug::dump($node->toArray());
		
		if($node->node_type === 'metaTitle') {
			$this->headTitle($node->content);
		}
		elseif($node->node_type === 'metaDescription') {
			$this->headMeta()->appendName('description', $node->content);
		}
		else {
			?>
			
			<div class="grid-100">
				<?php 
					echo $node->content;
				?>
			</div>
			<div class="clear"></div>
			
		<?php 
		}
    ?>
    	
    <?php 
    }
    ?>
</div>
