<?php
    $this->headMeta()->setIndent(' ');
	echo $this->doctype();
?>

<html>
<head>
<base href="<?php echo $this->serverUrl($this->baseUrl('/')); ?>" />
<?php
	echo $this->headMeta();
    echo $this->headTitle();
	echo $this->headLink()->appendStylesheet('/skins/' . Zend_Registry::get('skinName') . '/stylesheets/style.css', 'screen');
?>
</head>
<body>
    <div class="grid-container">
        <div class="wrapper">
            <header class="grid-100">
                <h1><?php echo Zend_Registry::get('siteName'); ?></h1>
                <nav>
                <?php 
					echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('Admin_Navigation'));
				?>
                </nav>
            </header>
            <div class="grid-100">
                <?php 
                    echo $this->layout()->content;
                ?>
            </div>
            <div class="push"></div>
        </div>
        <footer class="grid-100 align-center">
            <p><?php echo $this->copyright(); ?></p>
        </footer>
    </div>
</body>
</html>