<?php
    $this->headMeta()->setIndent(' ');
	echo $this->doctype();
?>

<html>
<head>
<base href="<?php echo $this->serverUrl($this->baseUrl('/')); ?>" />
<?php
	echo $this->headMeta();
    echo $this->headTitle();
	echo $this->headLink()->appendStylesheet('/skins/' . Zend_Registry::get('skinName') . '/stylesheets/style.css', 'screen');
?>
</head>
<body>
    <div class="grid-container">
        <div class="wrapper">
            <header class="grid-100">
                <nav class="grid-80">
                    <?php 
		              try {
			             echo $this->navigation()->menu();
		              } catch (Zend_Exception $e) {
                        //echo $e->getMessage();
		              }
			        ?>
                </nav>
                <div class="grid-20">
                    <h1><?php echo Zend_Registry::get('siteName'); ?></h1>
                </div>
            </header>
            <div class="grid-100">
                <?php 
                    echo $this->layout()->content;
                ?>
            </div>
            <div class="push"></div>
        </div>
        <footer class="grid-100 align-center">
            <p><?php echo $this->copyright(); ?></p>
        </footer>
    </div>
</body>
</html>