<div data-role="page" data-control-title="page-listing" id="page10">
    <div data-theme="a" data-role="header">
    	<a data-role="button" href="#Home" data-icon="arrow-l" data-iconpos="left" class="ui-btn-left">
            Back
        </a>
        <h3>
            Header
        </h3>
    </div>
    <div data-role="content">
        <ul data-role="listview" data-divider-theme="a" data-inset="true">
            <li data-role="list-divider" role="heading">
                Current Pages
            </li>
            <li data-theme="a">
                <a href="#page1" data-transition="slide">
                    Page Name
                </a>
            </li>
        </ul>
    </div>
    <div data-theme="a" data-role="footer" data-position="fixed">
        <h3>
            Footer
        </h3>
    </div>
</div>