<div data-role="page" id="createPage" data-theme="a">
	<div data-role="header">
	   <a data-role="button" href="#Home" data-icon="arrow-l" data-iconpos="left" class="ui-btn-left">
            Back
       </a>
       <h1>Create Page</h1>
	</div>
	<div role="main" class="ui-content">
        <?php
            echo $this->form;
        ?>
    </div>
    <div data-role="footer">
	   <h4>Footer</h4>
	</div><!-- /footer -->
</div>