<div data-role="page" id="displayEvent" data-theme="a">
	<div data-role="header" data-add-back-btn="true">
		<h3><?php echo $this->title($this->event->title); ?></h3>
    </div>
    <div role="main" class="ui-content">
    	<p><?php echo !empty($this->event->addrCity) ? $this->event->addrCity . ',' : '';?> <?php echo !empty($this->event->addrState) ? $this->event->addrState : ''; ?></p>
		<p>
		    <span><?php echo !empty($this->event->startDate) ? date('F j, Y', strtotime($this->event->startDate)) . ' - ' : ''; ?> <?php echo !empty($this->event->endDate) ? date('F j, Y', strtotime($this->event->endDate)) : ''; ?><br /></span>
		</p>
		<p>
		<?php 
		 echo $this->event->eventContent;
		?>
		</p>
    </div>
    <div data-role="footer">
		<h4>Page Footer</h4>
	</div><!-- /footer -->
</div>

		

