<div data-role="page" id="eventIndex" data-theme="a">
	<div data-role="header" data-add-back-btn="true">
		<h3>Events</h3>
    </div>
    <div role="main" class="ui-content">
    	<ul data-role="listview" data-divider-theme="b" data-inset="true">
    		<li data-role="list-divider" role="heading">
            </li>
    		<?php
	    		if($this->data instanceof Zend_Paginator) {
		          //Zend_Debug::dump($this->data);
		          
                    $this->partialLoop()->setObjectKey('model');

                    echo $this->partialLoop('events/partials/event-item.phtml', $this->data);
                    
                    if($this->data->count() > 1) {
                        //echo $this->paginationControl($this->data,'Sliding','front-pagination-control.phtml', array('page' => $this->page));
                    }

	         	}
            ?>
        </ul>      
    </div>
    <div data-role="footer">
		<h4>Page Footer</h4>
	</div><!-- /footer -->
</div>